import '@cli-coordinator/shared-config';
import '@cli-coordinator/shared-models';
import '@cli-coordinator/shared-utils';
import '@cli-coordinator/shared-ui';
import '@cli-coordinator/shared-http';
import '@cli-coordinator/shared-auth';
import '@cli-coordinator/shared-events';
import '@cli-coordinator/shared-validation';
import '@cli-coordinator/shared-permissions';
import '@cli-coordinator/shared-analytics';
import '@cli-coordinator/shared-storage';
import '@cli-coordinator/shared-queue';
import '@cli-coordinator/app3-data-access';
import '@cli-coordinator/app3-feature-home';
import '@cli-coordinator/app3-feature-editor';
import '@cli-coordinator/app3-feature-preview';
import '@cli-coordinator/app3-feature-history';
import '@cli-coordinator/app3-feature-collaboration';
import '@cli-coordinator/app3-ui-components';
import '@cli-coordinator/app3-ui-layout';
import '@cli-coordinator/app3-ui-toolbar';
import '@cli-coordinator/app3-util-validators';
import '@cli-coordinator/app3-feature-templates';
import '@cli-coordinator/app3-feature-export';
import '@cli-coordinator/app3-feature-import';
import '@cli-coordinator/app3-feature-comments';
import '@cli-coordinator/app3-feature-versioning';
import '@cli-coordinator/app3-feature-sharing';
import '@cli-coordinator/app3-feature-search';
import '@cli-coordinator/app3-feature-media';
import '@cli-coordinator/app3-feature-formatting';
import '@cli-coordinator/app3-feature-plugins';
import '@cli-coordinator/app3-feature-themes';
import '@cli-coordinator/app3-feature-analytics';
import '@cli-coordinator/app3-ui-panels';
import '@cli-coordinator/app3-ui-modals';
import '@cli-coordinator/app3-ui-forms';
import '@cli-coordinator/app3-ui-cards';
import '@cli-coordinator/app3-ui-tree';
import '@cli-coordinator/app3-util-markdown';
import '@cli-coordinator/app3-util-html';
import '@cli-coordinator/app3-util-diff';
import '@cli-coordinator/app3-util-compression';
import '@cli-coordinator/app3-data-sync';

import { bootstrapApplication } from '@angular/platform-browser';
import { appConfig } from './app/app.config';
import { App } from './app/app';

bootstrapApplication(App, appConfig).catch((err) => console.error(err));
