import '@cli-coordinator/shared-config';
import '@cli-coordinator/app2-data-access';
import '@cli-coordinator/app2-feature-home';
import '@cli-coordinator/app2-feature-search';
import '@cli-coordinator/app2-feature-detail';
import '@cli-coordinator/app2-feature-favorites';
import '@cli-coordinator/app2-feature-analytics';
import '@cli-coordinator/app2-ui-components';
import '@cli-coordinator/app2-ui-layout';
import '@cli-coordinator/app2-ui-charts';
import '@cli-coordinator/app2-util-validators';
import '@cli-coordinator/app2-util-transforms';
import '@cli-coordinator/app2-feature-compare';
import '@cli-coordinator/app2-feature-export';
import '@cli-coordinator/app2-feature-import';
import '@cli-coordinator/app2-feature-filters';
import '@cli-coordinator/app2-feature-tags';
import '@cli-coordinator/app2-feature-categories';
import '@cli-coordinator/app2-feature-reviews';
import '@cli-coordinator/app2-feature-ratings';
import '@cli-coordinator/app2-feature-bookmarks';
import '@cli-coordinator/app2-feature-sharing';
import '@cli-coordinator/app2-feature-notifications';
import '@cli-coordinator/app2-feature-history';
import '@cli-coordinator/app2-ui-cards';
import '@cli-coordinator/app2-ui-lists';
import '@cli-coordinator/app2-ui-forms';
import '@cli-coordinator/app2-ui-modals';
import '@cli-coordinator/app2-util-formatting';
import '@cli-coordinator/app2-util-sorting';
import '@cli-coordinator/app2-util-filtering';
import '@cli-coordinator/app2-util-dates';

import { bootstrapApplication } from '@angular/platform-browser';
import { appConfig } from './app/app.config';
import { App } from './app/app';

bootstrapApplication(App, appConfig).catch((err) => console.error(err));
