import '@cli-coordinator/shared-config';
import '@cli-coordinator/shared-models';
import '@cli-coordinator/shared-utils';
import '@cli-coordinator/shared-ui';
import '@cli-coordinator/shared-auth';
import '@cli-coordinator/shared-http';
import '@cli-coordinator/shared-logging';
import '@cli-coordinator/shared-cache';
import '@cli-coordinator/shared-events';
import '@cli-coordinator/shared-i18n';
import '@cli-coordinator/shared-crypto';
import '@cli-coordinator/shared-validation';
import '@cli-coordinator/shared-permissions';
import '@cli-coordinator/shared-analytics';
import '@cli-coordinator/shared-storage';
import '@cli-coordinator/shared-queue';
import '@cli-coordinator/app1-data-access';
import '@cli-coordinator/app1-feature-home';
import '@cli-coordinator/app1-feature-profile';
import '@cli-coordinator/app1-feature-settings';
import '@cli-coordinator/app1-feature-dashboard';
import '@cli-coordinator/app1-feature-notifications';
import '@cli-coordinator/app1-ui-components';
import '@cli-coordinator/app1-ui-layout';
import '@cli-coordinator/app1-ui-forms';
import '@cli-coordinator/app1-util-validators';
import '@cli-coordinator/app1-util-formatters';
import '@cli-coordinator/app1-feature-chat';
import '@cli-coordinator/app1-feature-calendar';
import '@cli-coordinator/app1-feature-analytics';
import '@cli-coordinator/app1-feature-search';
import '@cli-coordinator/app1-feature-files';
import '@cli-coordinator/app1-feature-tasks';
import '@cli-coordinator/app1-feature-comments';
import '@cli-coordinator/app1-feature-tags';
import '@cli-coordinator/app1-feature-export';
import '@cli-coordinator/app1-feature-import';
import '@cli-coordinator/app1-feature-billing';
import '@cli-coordinator/app1-feature-audit';
import '@cli-coordinator/app1-feature-webhooks';
import '@cli-coordinator/app1-feature-integrations';
import '@cli-coordinator/app1-ui-modals';
import '@cli-coordinator/app1-ui-tables';
import '@cli-coordinator/app1-ui-cards';
import '@cli-coordinator/app1-ui-navigation';
import '@cli-coordinator/app1-util-dates';
import '@cli-coordinator/app1-util-math';
import '@cli-coordinator/app1-util-strings';
import '@cli-coordinator/app1-util-colors';
import '@cli-coordinator/app1-util-csv';
import '@cli-coordinator/app1-data-sync';
import '@cli-coordinator/app1-data-cache';

import { bootstrapApplication } from '@angular/platform-browser';
import { appConfig } from './app/app.config';
import { App } from './app/app';

bootstrapApplication(App, appConfig).catch((err) => console.error(err));
